### ISSUE TITLE
【验收相关ISSUE】

### ISSUE THREAD

**Issue by huangjun12** [zwtu/TokShift-Transformer-Paddle#1]
1.  是否方便提供一个AIStudio项目，方便这边验收

**Comment by zwtu** [comment]
好的 这边正在整理公开

**Comment by zwtu** [comment]
已公开，https://aistudio.baidu.com/aistudio/projectdetail/3782324?contributionType=1&shared=1

**Comment by huangjun12** [comment]
2. 需要添加tipc相关内容，参考： https://github.com/PaddlePaddle/models/blob/release%2F2.2/tutorials/tipc/train_infer_python/README.md

**Comment by huangjun12** [comment]
3. test_tipc暂时跑不通
(1) 确保github里test_tipc自测通过 
(2) prepare.sh新增针对本模型的预训练权重下载步骤
(3) 请确保AIStudio项目里的tipc脚本及配置参数与github保持一致

**Comment by zwtu** [comment]
1. 已在自己主机上跑通TIPC

2.已在prepare新增 预训练权重的下载
3.已同步




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zwtu/TokShift-Transformer-Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月25日(星期一) 下午3:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zwtu/TokShift-Transformer-Paddle] 【验收相关ISSUE】 (Issue #1)





  
test_tipc暂时跑不通
 (1) 确保github里test_tipc自测通过
 (2) prepare.sh新增针对本模型的预训练权重下载步骤
 (3) 请确保AIStudio项目里的tipc脚本及配置参数与github保持一致
